version: 2
jobs:
  build:
    docker:
      - image: aripalo/gatsby-docker

    steps:
      - checkout

      - restore_cache:
          keys:
          - key-{{ checksum "package.json" }}

      - run:
          name: Install Npm
          command: npm install

      - save_cache:
          key: key-{{ checksum "package.json" }}
          paths:
            - node_modules
