version: 2
jobs:
  build:
    docker:
      - image: aripalo/gatsby-docker

    steps:
      - checkout

      - run:
          name: Install Npm
          command: npm install

      - run:
          name: Build
          command: gatsby build
